### PR TITLE
Rewrite with better types

### PR DESCRIPTION
**Pull request by devanshj**
Following up from https://github.com/alexreardon/bind-event-listener/pull/44#issuecomment-974520704
Supersedes #44

(Following up from https://github.com/alexreardon/bind-event-listener/pull/44#issuecomment-974589265) This PR has one downside: with `bindAll` if you bind events `"foo"` and `"click"` then you'd get events `Event` and `Event` instead of `Event` and `MouseEvent`, that is to say if any one event is untyped then all elements become untyped. [Test case](https://github.com/devanshj/bind-event-listener/blob/a72b302cf33a5ad76f00a31cca9b89d5fb0745d6/test/type-tests/bind-all.type-test.ts#L79-L80).

There is another downside (which I think isn't exclusive to my approach) is: If you bind a target `A | B`, both `A` and `B` have events `"foo"` but their event types are different namely `AFoo` and `BFoo`, in such case the `binding.listener` silently (even if `noImplictAny` is on) becomes `any` instead of `(event: AFoo | BFoo) => void`. [Test case](https://github.com/devanshj/bind-event-listener/blob/a72b302cf33a5ad76f00a31cca9b89d5fb0745d6/test/type-tests/bind.type-test.ts#L69-L87). This case would be super super rare though.

PR has my standards/opinions with them ;) feel free to keep/change/remove whatever you want. Also feel free to ask questions.

### CODE REVIEW

**Comment by alexreardon** [comment]
I will try to take a look at this soon 👍

**Comment by alexreardon** [comment]
Given the tradeoffs, do you think this is the way to go? Or still with #44 ?

**Comment by devanshj** [comment]
As I asked [here](https://github.com/alexreardon/bind-event-listener/pull/44#issuecomment-974589265), in #44 you can't do things like `bind({} as EventTarget, { type: "customEvent", listener })` which is a breaking change. Are you fine with that?

If yes then then I'll update this PR to not allow untyped events like #44 does and then this would have no zero downsides and will be better than #44

If no, then #44 gets rejected as it is now, and we're left with this and I'll let you decide if it's this is better than status quo. This PR trades off the experience when involving untyped events in `bindAll` for completions for typed events in both `bind` and `bindAll`.

Also consider this less of a PR and more of a reply to @Andarist :P so I'd want to know what he thinks and his approval too. (No hurries I don't mind keeping this open for long)

**Comment by alexreardon** [comment]
Sorry for not actioning this sooner. I appreciate the time you put into this. Things have been super busy for me lately. I hope to get to this PR when I have the right mental energy early next year. Merry Christmas!!

**Comment by devanshj** [comment]
Don't worry about it Alex, I understand. It was almost no work for me anyway haha, I don't mind any amount of delay. Merry Christmas!

**Comment by devanshj** [comment]
Let's reopen this if @Andarist wants, closing for now.

**Pull request closed without merging**
